project:
  type: website
  output-dir: docs
  resources:
    - "images/twitter-card.png"
  render:
    - "*.qmd"
    - "!materials/exercises"

website:
  page-navigation: true
  title: ""
  description: "Homepage for posit::conf(2023) workshop"
  site-url: "https://posit-conf-2023.github.io/dataviz-storytelling/"
  
  repo-url: https://github.com/posit-conf-2023/dataviz-storytelling
  repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    creator: "@CedScherer"
    image: "/images/twitter-card.png"

  favicon: "/images/favicon.png"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2023"
    background: "#D4EEE5"

  navbar:
    background: "#D4EEE5"
    logo: "images/logo.png"
    pinned: true
    align: center
    right:
      - icon: file-certificate
        href: license.qmd
      - icon: github
        href: https://github.com/posit-conf-2023/dataviz-storytelling
        text: GitHub
    left:
      - text: Information
        menu: 
          - text: Prework
            href: prework.qmd
          - text: Schedule
            href: schedule.qmd
          - text: Teaching Team
            href: team.qmd
      - text: Sessions
        menu: 
          - text: Foundations of Data Visualization
            href: modules/s01-foundations.qmd
          - text: Choose an Appropriate Display
            href: modules/s03-display.qmd
          - text: Think Like a Designer
            href: modules/s05-design.qmd
          - text: Guide the View(er)
            href: modules/s07-guide.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Asap SemiCondensed"

